# Generated by Django 4.0.3 on 2022-03-26 09:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blogcategory_blogtag_blogpost_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='categories',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='categories',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='main.blogcategory'),
            preserve_default=False,
        ),
    ]
